import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <main className="max-w-[960px] my-8 px-6 mx-auto">
      <h2 className="my-6 text-2xl font-bold">
        This layout will be shared between all nested components
      </h2>
      <section>
        <ul className="flex flex-wrap justify-between p-0 list-none">
          {children}
        </ul>
      </section>
    </main>
  );
}
